
# ── Aliases del curso ─────────────────────────────────────────────────────
alias ll='ls -la'
alias ports='ss -tulnp'
alias disk='df -h'
alias mem='free -h'
alias procs='ps aux --sort=-%cpu | head -15'
alias logs='tail -f /var/log/syslog'

# Prompt con color
PS1='\[\033[01;32m\]alumno@eva-terminal\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Bienvenida
clear
echo ""
echo "  +----------------------------------------------------------+"
echo "  |   Terminal de Practica -- Infraestructura Tecnologica   |"
echo "  |   help-infra <1|2|3|4|5>  para comandos de cada unidad  |"
echo "  |   NOTA: contenedor Ubuntu; servidor real usa Fedora      |"
echo "  +----------------------------------------------------------+"
echo ""

# ── Cheat-sheet por unidad ────────────────────────────────────────────────
help-infra() {
  local u=${1:-all}
  case $u in

    1|linux)
      echo ""
      echo "╔══ Unidad 1 - Servidores Linux ══════════════════════════════╗"
      echo "║ Sistema de archivos                                          ║"
      echo "║  pwd  ls -la  cd /ruta  mkdir -p a/b  cp -r src dst         ║"
      echo "║  mv origen dest    rm -rf dir    find / -name '*.conf'       ║"
      echo "║  locate nginx.conf   tree /etc/apache2/                      ║"
      echo "║                                                              ║"
      echo "║ Usuarios y permisos                                          ║"
      echo "║  sudo useradd -m -s /bin/bash alumno01                      ║"
      echo "║  sudo passwd alumno01                                        ║"
      echo "║  sudo usermod -aG sudo alumno01                             ║"
      echo "║  sudo groupadd infraestructura                               ║"
      echo "║  id alumno01     groups alumno01                             ║"
      echo "║  chmod 755 archivo    chmod u+x script.sh                   ║"
      echo "║  sudo chown -R www-data:www-data /var/www/html               ║"
      echo "║                                                              ║"
      echo "║ Procesos y recursos                                          ║"
      echo "║  top   htop   ps aux   ps aux | grep apache                  ║"
      echo "║  kill -9 PID   sudo killall nginx                            ║"
      echo "║  df -h   du -sh /var/*   free -h                            ║"
      echo "║  vmstat 1   mpstat 1   iostat -x 1                          ║"
      echo "║  uptime                                                      ║"
      echo "║                                                              ║"
      echo "║ Red                                                          ║"
      echo "║  ip addr show    ip route show                               ║"
      echo "║  ss -tulnp       ping -c4 8.8.8.8                           ║"
      echo "║  curl -I http://moodle-app                                   ║"
      echo "║                                                              ║"
      echo "║ Servicios (wrapper systemctl -> service en Ubuntu)           ║"
      echo "║  sudo systemctl start apache2                                ║"
      echo "║  sudo systemctl stop nginx                                   ║"
      echo "║  sudo systemctl status apache2                               ║"
      echo "║  sudo systemctl list-units                                   ║"
      echo "║                                                              ║"
      echo "║ Logs (wrapper journalctl -> /var/log/ en Ubuntu)             ║"
      echo "║  journalctl -f                # tail /var/log/syslog         ║"
      echo "║  journalctl -u apache2 -f     # tail apache2/error.log       ║"
      echo "║  journalctl -p err            # errores recientes            ║"
      echo "║  tail -f /var/log/syslog      # equivalente directo          ║"
      echo "╚══════════════════════════════════════════════════════════════╝"
      ;;

    2|web)
      echo ""
      echo "╔══ Unidad 2 - Servicios Web ══════════════════════════════════╗"
      echo "║ Apache                                                        ║"
      echo "║  sudo systemctl start apache2                                 ║"
      echo "║  sudo systemctl stop  apache2                                 ║"
      echo "║  sudo systemctl status apache2                                ║"
      echo "║  curl -I http://localhost                                     ║"
      echo "║  cat /etc/apache2/sites-enabled/000-default.conf             ║"
      echo "║  ls  /etc/apache2/sites-enabled/                             ║"
      echo "║  ls  /var/log/apache2/                                       ║"
      echo "║  sudo a2enmod rewrite && sudo systemctl restart apache2      ║"
      echo "║                                                               ║"
      echo "║ Nginx                                                         ║"
      echo "║  sudo systemctl start nginx                                   ║"
      echo "║  sudo systemctl stop  nginx                                   ║"
      echo "║  cat /etc/nginx/sites-enabled/default                        ║"
      echo "║  ls  /etc/nginx/conf.d/                                      ║"
      echo "║  ls  /var/log/nginx/                                         ║"
      echo "║                                                               ║"
      echo "║ PHP                                                            ║"
      echo "║  php --version                                                ║"
      echo "║  php -r 'echo phpinfo();' | head -20                         ║"
      echo "║  cat /etc/php/8.1/fpm/php.ini | grep memory_limit            ║"
      echo "║                                                               ║"
      echo "║ SSL / OpenSSL                                                  ║"
      echo "║  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \\       ║"
      echo "║    -keyout /tmp/k.key -out /tmp/c.crt -subj '/CN=localhost'  ║"
      echo "║  openssl x509 -in /tmp/c.crt -text -noout | head -30        ║"
      echo "║  openssl s_client -connect moodle-app:443 2>&1 | head -20   ║"
      echo "╚══════════════════════════════════════════════════════════════╝"
      ;;

    3|db)
      echo ""
      echo "╔══ Unidad 3 - Bases de Datos ═════════════════════════════════╗"
      echo "║ PostgreSQL (BD real del curso)                                ║"
      echo "║  psql -h moodle-db -U moodle_user -d moodle_db               ║"
      echo "║  Contrasena: Moodle@Secure2024                                ║"
      echo "║                                                               ║"
      echo "║  Dentro de psql:                                              ║"
      echo "║    \\l                 listar bases de datos                  ║"
      echo "║    \\c moodle_db       conectar a BD                          ║"
      echo "║    \\dt                listar tablas                          ║"
      echo "║    \\d mdl_user        describir tabla                        ║"
      echo "║    \\du                listar usuarios                        ║"
      echo "║    \\timing            medir tiempo de consultas              ║"
      echo "║    \\q                 salir                                  ║"
      echo "║                                                               ║"
      echo "║  SELECT username, email FROM mdl_user WHERE deleted=0;       ║"
      echo "║  SELECT fullname FROM mdl_course WHERE id=2;                  ║"
      echo "║  SELECT name FROM mdl_assign WHERE course=2;                  ║"
      echo "║                                                               ║"
      echo "║  pg_dump -h moodle-db -U moodle_user moodle_db > backup.sql  ║"
      echo "║  pg_dump -h moodle-db -U moodle_user -F c \\                  ║"
      echo "║    -f /tmp/backup.dump moodle_db                             ║"
      echo "║                                                               ║"
      echo "║ MySQL client (demo)                                            ║"
      echo "║  mysql --version                                              ║"
      echo "║  mysqldump --help | head -5                                   ║"
      echo "╚══════════════════════════════════════════════════════════════╝"
      ;;

    4|docker)
      echo ""
      echo "╔══ Unidad 4 - Docker (contenedores REALES del EVA) ═══════════╗"
      echo "║ Contenedores y ciclo de vida                                   ║"
      echo "║  docker ps                    contenedores activos            ║"
      echo "║  docker ps -a                 todos los contenedores          ║"
      echo "║  docker images                imagenes disponibles            ║"
      echo "║  docker pull nginx:1.25       descargar imagen                ║"
      echo "║  docker run -d --name test -p 8888:80 nginx:1.25             ║"
      echo "║  docker stop test && docker rm test                          ║"
      echo "║                                                               ║"
      echo "║ Inspeccion y logs                                              ║"
      echo "║  docker logs moodle-app       logs de Moodle                 ║"
      echo "║  docker logs moodle-db        logs de PostgreSQL             ║"
      echo "║  docker logs -f moodle-app    logs en tiempo real            ║"
      echo "║  docker stats                 CPU/RAM de contenedores        ║"
      echo "║  docker inspect moodle-app    detalles del contenedor        ║"
      echo "║  docker exec -it moodle-app bash   entrar al contenedor      ║"
      echo "║                                                               ║"
      echo "║ Redes y volumenes                                              ║"
      echo "║  docker network ls                                            ║"
      echo "║  docker network inspect moodle-lms_moodle-network            ║"
      echo "║  docker volume ls                                             ║"
      echo "║  docker volume inspect moodle-lms_moodledata                 ║"
      echo "║                                                               ║"
      echo "║ Build y Compose                                                ║"
      echo "║  mkdir /tmp/mi-app && cd /tmp/mi-app                         ║"
      echo "║  echo 'FROM nginx:alpine' > Dockerfile                       ║"
      echo "║  docker build -t mi-prueba:1.0 .                             ║"
      echo "║  docker run -d --name prueba -p 9090:80 mi-prueba:1.0        ║"
      echo "║  docker compose version                                       ║"
      echo "╚══════════════════════════════════════════════════════════════╝"
      ;;

    5|sec)
      echo ""
      echo "╔══ Unidad 5 - Seguridad y Respaldo ══════════════════════════╗"
      echo "║ Firewall (ufw en Ubuntu / firewall-cmd wrapper)               ║"
      echo "║  sudo ufw status verbose                                      ║"
      echo "║  sudo ufw allow http                                          ║"
      echo "║  sudo ufw allow 8080/tcp                                      ║"
      echo "║  firewall-cmd --list-all     (wrapper -> ufw)                ║"
      echo "║  firewall-cmd --add-port=9090/tcp                            ║"
      echo "║                                                               ║"
      echo "║ fail2ban                                                       ║"
      echo "║  sudo fail2ban-client status                                  ║"
      echo "║  cat /etc/fail2ban/jail.conf | head -40                      ║"
      echo "║                                                               ║"
      echo "║ iptables                                                       ║"
      echo "║  sudo iptables -L -n -v                                       ║"
      echo "║  sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT          ║"
      echo "║                                                               ║"
      echo "║ SELinux / AppArmor (Ubuntu usa AppArmor)                      ║"
      echo "║  getenforce                  (muestra equivalente apparmor)  ║"
      echo "║  sudo aa-status | head -10                                    ║"
      echo "║                                                               ║"
      echo "║ SSH                                                            ║"
      echo "║  ssh-keygen -t rsa -b 4096 -C 'alumno@eva'                   ║"
      echo "║  cat ~/.ssh/id_rsa.pub                                        ║"
      echo "║  ssh -o StrictHostKeyChecking=no root@192.168.56.104         ║"
      echo "║                                                               ║"
      echo "║ Backup y compresion                                            ║"
      echo "║  tar -czf /tmp/backup_\$(date +%Y%m%d).tar.gz /etc/nginx/     ║"
      echo "║  tar -tzf /tmp/backup_*.tar.gz                                ║"
      echo "║  rsync -avz /etc/nginx/ /tmp/backup_nginx/                   ║"
      echo "║                                                               ║"
      echo "║ Monitoreo                                                      ║"
      echo "║  top   htop   ps aux                                          ║"
      echo "║  mpstat 1 5    iostat -x 1 5                                  ║"
      echo "║  iftop -n      tcpdump -i eth0 -c 20                         ║"
      echo "║  df -h   du -sh /var/*   free -h   vmstat 1                  ║"
      echo "║  crontab -e    crontab -l                                     ║"
      echo "╚══════════════════════════════════════════════════════════════╝"
      ;;

    *)
      echo ""
      echo "Uso: help-infra <numero>"
      echo "  help-infra 1   Servidores Linux"
      echo "  help-infra 2   Servicios Web (Apache, Nginx, PHP, SSL)"
      echo "  help-infra 3   Bases de Datos (PostgreSQL real del curso)"
      echo "  help-infra 4   Docker (contenedores reales del EVA)"
      echo "  help-infra 5   Seguridad y Respaldo"
      echo ""
      echo "Alias rapidos: ll  ports  disk  mem  procs  logs"
      ;;
  esac
  echo ""
}
export -f help-infra
